#Configuration for Eureka :

# We can change the application name and as many as properties we want from here
# spring:
#   application:
#     name: Config-Default

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: http://localhost:8088/eureka
